/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Consultas;
import Controlador.ControladorBD;
import Modelo.Usuario;
import Controlador.ControladorUsuario;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

//import javax.swing.JTextField;

/**
 *
 * @author santy
 */
public class GIngreso extends javax.swing.JFrame {
    
    ControladorUsuario controladorUsuarios;
    Usuario UsuAut;
    ControladorBD cx;

    /**
     * Creates new form GIngreso
     */
    public GIngreso() {
        controladorUsuarios= new ControladorUsuario();
        
        initComponents();
        //centrar formulario
        this.setLocationRelativeTo(this);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameUser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Contra = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Iniciar Sesion");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("CONTRASEÑA");

        nameUser.setText("Ingrese Correo");
        nameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUserActionPerformed(evt);
            }
        });

        jButton1.setText("ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Contra.setText("jPasswordField1");
        Contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraActionPerformed(evt);
            }
        });

        jButton2.setText("cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear Cuenta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton1)
                        .addGap(63, 63, 63)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameUser)
                            .addComponent(jLabel1))))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jLabel3)
                    .addContainerGap(418, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(nameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLabel3)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Consultas con = new Consultas();
     String email = nameUser.getText();
    String password = new String(Contra.getPassword());
    
     try {
        validateEmail(email);
        validatePassword(password);

        // El correo electrónico y la contraseña cumplen con los criterios
        // Realizar las acciones necesarias aquí
    } catch (IllegalArgumentException e) {
        // El correo electrónico o la contraseña no cumplen con los criterios
        JOptionPane.showMessageDialog(null, e.getMessage());
        
        
        
        
    
}

    
boolean loginExitoso = con.accesoUsuario(nameUser.getText(), Contra.getText());

if (loginExitoso) {
    // Inicio de sesión exitoso, redirigir a la parte de Gvendedor
    Principal gvendedor = new Principal();
    gvendedor.setVisible(true);
    // Aquí puedes ocultar o cerrar la ventana actual si es necesario
} else {
    // Inicio de sesión fallido, mostrar mensaje de error
    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
}






    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
        Gregistro ga= new Gregistro();
        ga.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUserActionPerformed
         String email = nameUser.getText();
    try {
        validateEmail(email);
        // El correo electrónico tiene un formato válido
        // Puedes realizar las acciones necesarias aquí
    } catch (IllegalArgumentException e) {
        // El correo electrónico tiene un formato inválido
        JOptionPane.showMessageDialog(null, "Ingrese un correo electrónico válido");
    }
}

// Método para validar el formato de un correo electrónico y lanzar una excepción si no es válido
private void validateEmail(String email) {
  String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    Pattern pattern = Pattern.compile(emailRegex);
    Matcher matcher = pattern.matcher(email);
    if (!matcher.matches()) {
        throw new IllegalArgumentException("Ingrese un correo electrónico válido");
    }
    }//GEN-LAST:event_nameUserActionPerformed

    private void ContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraActionPerformed
     String username = nameUser.getText();
    String password = new String(Contra.getPassword());

    try {
        validateUsername(username);
        validatePassword(password);

        // El nombre de usuario y la contraseña cumplen con los criterios
        // Realizar las acciones necesarias aquí
    } catch (IllegalArgumentException e) {
        // El nombre de usuario o la contraseña no cumplen con los criterios
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
// Método para validar el nombre de usuario
private void validateUsername(String username) {
    // No es necesario validar el nombre de usuario según los criterios proporcionados
    // Puedes agregar cualquier validación adicional si es necesario
}

// Método para validar la contraseña
private void validatePassword(String password) {
 // Validar longitud mínima
    if (password.length() < 8) {
        throw new IllegalArgumentException("La contraseña debe tener al menos 8 caracteres");
    }
    // Validar que comience con una letra mayúscula
    if (!Character.isUpperCase(password.charAt(0))) {
        throw new IllegalArgumentException("La contraseña debe comenzar con una letra mayúscula");
    }

    // Validar que contenga al menos 1 dígito
    boolean hasDigit = false;
    for (char c : password.toCharArray()) {
        if (Character.isDigit(c)) {
            hasDigit = true;
            break;
        }
    }
    if (!hasDigit) {
        throw new IllegalArgumentException("La contraseña debe contener al menos 1 dígito");
    }

    // Validar que contenga al menos 1 carácter especial
    String specialChars = "~`!@#$%^&*()-_=+\\|[{]};:'\",<.>/?";
    boolean hasSpecialChar = false;
    for (char c : password.toCharArray()) {
        if (specialChars.indexOf(c) != -1) {
            hasSpecialChar = true;
            break;
        }
    }
    if (!hasSpecialChar) {
        throw new IllegalArgumentException("La contraseña debe contener al menos 1 carácter especial");
    }

        
        
        
    }//GEN-LAST:event_ContraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GIngreso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameUser;
    // End of variables declaration//GEN-END:variables
}
