/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Luisa Lopez Castro
 */
public class GMascotas extends javax.swing.JFrame {

    /**
     * Creates new form GMascotas
     */
    public GMascotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Gatos = new javax.swing.JButton();
        Pajaros = new javax.swing.JButton();
        Perro = new javax.swing.JButton();
        Peces = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecione el tipo de mascota que desea");

        Gatos.setText("Gatos");
        Gatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GatosActionPerformed(evt);
            }
        });

        Pajaros.setText("Pájaros");
        Pajaros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PajarosActionPerformed(evt);
            }
        });

        Perro.setText("Perros");
        Perro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerroActionPerformed(evt);
            }
        });

        Peces.setText("Peces");
        Peces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PecesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Perro)
                        .addGap(12, 12, 12)
                        .addComponent(Peces)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pajaros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gatos)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gatos)
                    .addComponent(Perro)
                    .addComponent(Peces)
                    .addComponent(Pajaros))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerroActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GPerro().setVisible(true);
        });
    }//GEN-LAST:event_PerroActionPerformed

    private void PecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PecesActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GPeces().setVisible(true);
        });
    }//GEN-LAST:event_PecesActionPerformed

    private void PajarosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PajarosActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GPajaros().setVisible(true);
        });
    }//GEN-LAST:event_PajarosActionPerformed

    private void GatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GatosActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GGato().setVisible(true);
        });
    }//GEN-LAST:event_GatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GMascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gatos;
    private javax.swing.JButton Pajaros;
    private javax.swing.JButton Peces;
    private javax.swing.JButton Perro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
